{% set name = "tabmat" %}
{% set version = "4.0.0a3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c795687f66d38a8d2ebbb4b89905c49e2b233b1300ad031846f239c365dc7f2a


build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - GLM_ARCHITECTURE=default


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - cython
    - jemalloc-local  # [not win]
    - llvm-openmp     # [osx]
    - mako
    - numpy
    - pip
    - setuptools_scm
    - xsimd <11|>12.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pandas
    - scipy
    - formulaic >=0.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tabmat

about:
  home: https://github.com/Quantco/tabmat
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Efficient matrix representations for working with tabular data '
  description: |
    tabmat provides efficient tools for representing tabular data as a mix of
    dense, sparse and categorical subcomponents, resulting in 100x faster 
    performance on some machine learning problems!
  doc_url: https://tabmat.readthedocs.io/
  dev_url: https://github.com/Quantco/tabmat

extra:
  recipe-maintainers:
    - MarcAntoineSchmidtQC
    - xhochy
    - tbenthompson
    - jtilly
